#!/bin/bash
#
# Run dmenu with color scheme generated by wal 

#Color config
wal=/home/cptn/Downloads/die_misere_pixel_fullhd.png
color0=#000000
color1=#967062
color2=#AA8878
color3=#DEB156
color4=#697B96
color5=#A99B95
color6=#CEA897
color7=#D5D7DA
color8=#666666
color9=#967062
color10=#AA8878
color11=#DEB156
color12=#697B96
color13=#A99B95
color14=#CEA897
color15=#D5D7DA

dmenu_run -nb "$color0" -nf "$color7" -sb "$color0" -sf "$color3"
